kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DBAdmin
  namespace: backup
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: DeveloperBinding
  namespace: backup
subjects:
  - kind: User
    name: "Jessica"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: DBAdmin
  apiGroup: rbac.authorization.k8s.io
